### ISSUE TITLE
npx i command not found

### ISSUE THREAD

**Issue by wrussell1999** [tomMisson/ManMetHacks2.0-site#7]
Pretty sure this should be `npm i` not `npx i`. I'm not expert but I can't find anything about `npx i` and npm seems more ideal for that rather than npx, which is a package runner!

**Comment by wrussell1999** [comment]
Fixed in [my PR](https://github.com/tomMisson/ManMetHacks2.0-site/pull/8)

**Comment by tomMisson** [comment]
Yeah, normally npm i, that installs all dependancies in the package .json
